[project]
name = "trivia-backend"
requires-python = ">=3.12"
version = "1.0.0"
description = "TriviaPay Backend API"
dependencies = []

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

